# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 536)
        MainWindow.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:7px;\n"
"width:50px;\n"
"height:50px;\n"
"font-size:15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color:black;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color:silver;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:white;\n"
"font-size:30px;\n"
"margin: 1px;\n"
"bourder-radius:10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 150, 371, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_16.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_15.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_14.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_7.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_9.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_10.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_11.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_17.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 4, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 371, 61))
        self.label.setStyleSheet("border-radius:10px;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.f = '0'
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_16.setText(_translate("MainWindow", "0"))
        self.pushButton_15.setText(_translate("MainWindow", "3"))
        self.pushButton_14.setText(_translate("MainWindow", "4"))
        self.pushButton.setText(_translate("MainWindow", "*"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        self.pushButton_7.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "+"))
        self.pushButton_5.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "="))
        self.pushButton_9.setText(_translate("MainWindow", "8"))
        self.pushButton_10.setText(_translate("MainWindow", "5"))
        self.pushButton_11.setText(_translate("MainWindow", "2"))
        self.pushButton_12.setText(_translate("MainWindow", "."))
        self.pushButton_13.setText(_translate("MainWindow", "7"))
        self.pushButton_17.setText(_translate("MainWindow", "С"))
        self.label.setText(_translate("MainWindow", "0"))

        self.pushButton_17.clicked.connect(self.delete)
        self.pushButton_16.clicked.connect(lambda: self.on_press(self.pushButton_16.text()))
        self.pushButton_15.clicked.connect(lambda: self.on_press(self.pushButton_15.text()))
        self.pushButton_14.clicked.connect(lambda: self.on_press(self.pushButton_14.text()))
        self.pushButton_13.clicked.connect(lambda: self.on_press(self.pushButton_13.text()))
        self.pushButton_12.clicked.connect(lambda: self.on_press(self.pushButton_12.text()))
        self.pushButton_11.clicked.connect(lambda: self.on_press(self.pushButton_11.text()))
        self.pushButton_10.clicked.connect(lambda: self.on_press(self.pushButton_10.text()))
        self.pushButton_9.clicked.connect(lambda: self.on_press(self.pushButton_9.text()))
        self.pushButton_7.clicked.connect(lambda: self.on_press(self.pushButton_7.text()))
        self.pushButton_6.clicked.connect(lambda: self.on_press(self.pushButton_6.text()))
        self.pushButton_5.clicked.connect(lambda: self.on_press(self.pushButton_5.text()))
        self.pushButton_4.clicked.connect(lambda: self.on_press(self.pushButton_4.text()))
        self.pushButton_3.clicked.connect(lambda: self.on_press(self.pushButton_3.text()))
        self.pushButton_2.clicked.connect(lambda: self.on_press(self.pushButton_2.text()))
        self.pushButton.clicked.connect(lambda: self.on_press(self.pushButton.text()))

        self.pushButton_8.clicked.connect(self.run)

    def on_press(self,a):

        if self.f =='0':
            self.f =''
        self.f+=a
        self.label.setText(self.f)
    def run(self):
        try:
            self.f = self.label.text()
            self.label.setText(str(eval(self.f)))
        except:
            self.label.setText('Введи что нибудь')
    def delete(self):
        self.f=self.label.text()
        self.label.setText(str(''))